apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-sc-dev
  namespace: spark-operator
spec:
  type: Scala
  mode: cluster
  image: "docker.io/bitnamilegacy/spark:3.5.1"
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.sql.connect.SimpleSparkConnectService
  mainApplicationFile: "local:///opt/bitnami/spark/jars/spark-connect_2.12-3.5.1.jar"
  sparkVersion: "3.5.1"
  batchScheduler: "volcano"
  sparkConf:
    "spark.dynamicAllocation.enabled": "true"
    "spark.dynamicAllocation.shuffleTracking.enabled": "true"
    "spark.dynamicAllocation.minExecutors": "0"
    "spark.dynamicAllocation.maxExecutors": "5"
    "spark.dynamicAllocation.executorIdleTimeout": "60s"
    "spark.dynamicAllocation.schedulerBacklogTimeout": "1s"
    "spark.kubernetes.scheduler.name": "volcano"
    "spark.connect.grpc.binding.port": "15002"
  driver:
    cores: 1
    coreRequest: "200m"
    coreLimit: "500m"
    memory: "512m"
    serviceAccount: spark-service-account
    ports:
      - name: spark-connect
        containerPort: 15002
        protocol: TCP
  executor:
    cores: 1
    coreRequest: "200m"
    coreLimit: "500m"
    memory: "512m"
